openapi: 3.0.1
info:
  title: Talk to LLM
  description: A plugin that allows the user to talk to LLM
  version: 'v1'
servers:
  - url: https://f9ab-103-171-129-48.ngrok-free.app
paths:
  /talk:
    post:
      operationId: talk
      summary: Talk to LLM
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TalkRequest'
      responses:
        '200':
          description: Talking successful
components:
  schemas:
    TalkRequest:
      type: object
      required:
        - text
      properties:
        text:
          type: string
          description: Text to talk
          required: true
