openapi: 3.0.1
info:
  title: Translation Plugin API
  description: A plugin that allows the user to translate text using ChatGPT. If you do not know the user's username, ask them first before making queries to the plugin. Otherwise, use the username "global".
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /translate:
    post:
      operationId: translate
      summary: Translate text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TranslateRequest'
      responses:
        '200':
          description: Translation successful
components:
  schemas:
    TranslateRequest:
      type: object
      required:
        - text
      properties:
        text:
          type: string
          description: Text to translate
          required: true
